[CmdletBinding()]
param([Parameter(Mandatory)][string]$PlanPath,[Parameter(Mandatory)][string]$ManifestPath)
. "$PSScriptRoot/common.ps1"
$plan = Read-Json $PlanPath
$manifest = Read-Json $ManifestPath
if ($plan.PSObject.Properties.Name -notcontains 'presentation_spec') { return } # Legacy technical examples.
$spec = $plan.presentation_spec
foreach ($key in @('speaker','presentation_date')) { if ([string]::IsNullOrWhiteSpace((Value-Or $spec $key ''))) { throw "Missing confirmed cover field: $key" } }
$registry = @{}; $seenImages = @{}
foreach ($a in $manifest.assets) {
    $kind = Value-Or $a 'asset_kind' ''
    if ($kind -notin @('icon','illustration','logo')) { throw "Missing asset_kind: $($a.id)" }
    if ($kind -eq 'icon' -and $a.origin -ne 'imagegen') { throw 'Semantic icons must be generated by ImageGen' }
    $registry[$a.id] = $a
}
$page = 0
foreach ($s in $plan.slides) {
    $page++
    $visible = $s.title + ' ' + (@($s.elements | Where-Object type -eq 'text' | ForEach-Object text) -join ' ')
    if ($s.kind -eq 'cover') { foreach ($key in @('speaker','presentation_date')) { if (-not $visible.Contains([string]$spec.$key)) { throw "Cover does not display $key" } } }
    if ($s.kind -eq 'body') {
        foreach ($key in @('chapter_id','chapter_title','subtitle','logic_relation','icon_plan','image_plan')) { if ($s.PSObject.Properties.Name -notcontains $key) { throw "Page $page missing $key" } }
        if (-not $s.title.StartsWith([string]$s.chapter_id + '、')) { throw "Chapter numbering missing: page $page" }
        if (-not $visible.Contains([string]$s.subtitle)) { throw "Subtitle not rendered: page $page" }
    }
    $hasIllustration = $false
    foreach ($e in @($s.elements | Where-Object type -eq 'image')) {
        if (-not $registry.ContainsKey($e.asset_id)) { throw 'Image not registered' }
        $a = $registry[$e.asset_id]
        if ($a.asset_kind -ne 'illustration') { continue }
        $hasIllustration = $true
        foreach ($key in @('id','sha256','parent_asset_id')) {
            $v = [string](Value-Or $a $key '')
            if ([string]::IsNullOrWhiteSpace($v)) { continue }
            $token = "$key/$v"
            if ($seenImages.ContainsKey($token) -and $seenImages[$token] -ne $page) { throw "Illustration reused across pages: $($a.id)" }
            $seenImages[$token] = $page
        }
    }
    if ($s.kind -eq 'toc' -and -not $hasIllustration -and [string]::IsNullOrWhiteSpace((Value-Or $spec 'toc_image_exception' ''))) { throw 'TOC requires its own theme illustration or user-confirmed exception' }
}
'Presentation specification checks: PASS'
